#!/bin/sh

export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/Software/nomad-lsp"
export EDITOR=nvim

# Load profiles from /etc/profile.d
if test -d $HOME/.profile.d/; then
	for profile in $HOME/.profile.d/*.sh; do
		test -r "$profile" && . "$profile"
	done
	unset profile
fi

TZ='Europe/Paris'; export TZ
