return {
  {
    "williamboman/mason.nvim",
    -- version = "^1.0.0",
    opts = {
      ensure_installed = {
        "black",
        "clangd",
        "cmakelang",
        "cmakelint",
        "codelldb",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "elixir-ls",
        "gofumpt",
        "goimports",
        "golangci-lint",
        "golangci-lint-langserver",
        "gomodifytags",
        "gopls",
        "hclfmt",
        "java-language-server",
        "json-lsp",
        "lua-language-server",
        "markdown-toc",
        "markdownlint-cli2",
        "marksman",
        "neocmakelsp",
        "php-cs-fixer",
        "phpactor",
        "phpcs",
        "prettier",
        "pyright",
        "ruff",
        "ruff-lsp",
        "shellcheck",
        "shfmt",
        "sqlls",
        "stylua",
        "svelte-language-server",
        "tailwindcss-language-server",
        "yaml-language-server",
      },
    },
  },
  -- { "mason-org/mason-lspconfig.nvim", version = "^1.0.0" },
  {
    "jay-babu/mason-nvim-dap.nvim",
    opts = {
      ensure_installed = {
        "python",
        "delve",
      },
      automatic_installation = true,
    },
  },
}
