return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "css",
      "dockerfile",
      "html",
      "javascript",
      "json",
      "json5",
      "latex",
      "lua",
      "markdown",
      "python",
      "rust",
      "typescript",
      "yaml",
      "elixir",
      "go",
      "svelte",
      "just",
      "hcl",
      "toml",
    },
  },
}
