return {

  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    event = "BufReadPost",
    opts = {
      ensure_installed = {
        "bash",
        "bibtex",
        "c",
        "cmake",
        "cpp",
        "css",
        "c_sharp",
        "dockerfile",
        "elixir",
        "fish",
        "hcl",
        "html",
        "haskell",
        "javascript",
        "json",
        "json5",
        -- "just",
        "go",
        "latex",
        "lua",
        "make",
        "markdown",
        "mermaid",
        "ninja",
        "python",
        "rust",
        "svelte",
        "typescript",
        "yaml",
      },
      sync_install = true,
      context_commentstring = {
        enable = true,
      },
      highlight = {
        enable = true,
      },
      -- incremental_selection = {
      --     enable = true,
      --     keymaps = {
      --         init_selection = 'vb',
      --         scope_incremental = '<CR>',
      --         node_incremental = '<TAB>',
      --         node_decremental = '<S-TAB>',
      --     },
      -- },
      playground = {
        enable = true,
        disable = {},
        updatetime = 25,
        persist_queries = false,
        keybindings = {
          toggle_query_editor = "o",
          toggle_hl_groups = "i",
          toggle_injected_languages = "t",
          toggle_anonymous_nodes = "a",
          toggle_language_display = "I",
          focus_language = "f",
          unfocus_language = "F",
          update = "R",
          goto_node = "<cr>",
          show_help = "?",
        },
      },
    },
    main = "nvim-treesitter.configs",
  },
  { "nvim-treesitter/playground" },
}
