config:
  backup: true
  banner: true
  create: true
  dotpath: ../dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_polybar:
    dst: ~/.config/polybar
    src: config/polybar
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_clang-format_c:
    src: clang-format_c
    dst: ~/.clang-format_c
  f_clang-tidy:
    src: clang-tidy
    dst: ~/.clang-tidy
  f_emacs:
    src: emacs
    dst: ~/.emacs
  d_emacs.d:
    src: emacs.d
    dst: ~/.emacs.d
    chmod: '700'
  f_clang-format_cpp:
    src: clang-format_cpp
    dst: ~/.clang-format_cpp
  d_kdedefaults:
    src: config/kdedefaults
    dst: ~/.config/kdedefaults
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  f_dolphinrc:
    src: config/dolphinrc
    dst: ~/.config/dolphinrc
    chmod: '600'
  f_krunnerrc:
    src: config/krunnerrc
    dst: ~/.config/krunnerrc
    chmod: '600'
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_eww:
    src: config/eww
    dst: ~/.config/eww
  d_autostart:
    src: config/autostart
    dst: ~/.config/autostart
  f_tmux.conf:
    src: tmux.conf
    dst: ~/tmux.conf
  f_tmux-dark.conf:
    src: tmux-dark.conf
    dst: ~/tmux-dark.conf
  f_tmux-light.conf:
    src: tmux-light.conf
    dst: ~/tmux-light.conf
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  d_wallpapers:
    src: config/wallpapers
    dst: ~/.config/wallpapers
  f_autostart.sh:
    src: config/autostart.sh
    dst: ~/.config/autostart.sh
    chmod: '755'
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  d_bin:
    src: local/bin
    dst: ~/.local/bin
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  f_editorconfig:
    src: editorconfig
    dst: ~/.editorconfig
  d_fastfetch:
    src: config/fastfetch
    dst: ~/.config/fastfetch
  f_monitorcontrol:
    src: local/bin/monitorcontrol
    dst: ~/.local/bin/monitorcontrol
    chmod: '755'
  f_xlight:
    src: local/bin/xlight
    dst: ~/.local/bin/xlight
    chmod: '755'
  f_idlelock:
    src: local/bin/idlelock
    dst: ~/.local/bin/idlelock
    chmod: '755'
  f_chwp:
    src: local/bin/chwp
    dst: ~/.local/bin/chwp
    chmod: '755'
  f_term.sh:
    src: profile.d/term.sh
    dst: ~/.profile.d/term.sh
  f_profile:
    src: profile
    dst: ~/.profile
  f_theming.sh:
    src: profile.d/theming.sh
    dst: ~/.profile.d/theming.sh
    chmod: '755'
  d_screenlayout:
    src: screenlayout
    dst: ~/.screenlayout
  f_forgit.plugin.sh:
    src: Software/forgit/forgit.plugin.sh
    dst: ~/Software/forgit/forgit.plugin.sh
    chmod: '755'
profiles:
  home:
    dotfiles:
    - f_vimrc
    - f_xinitrc
    - d_polybar
  /home/lukac/dotfiles/dotdrop/config.yaml:
    dotfiles:
    - d_nvim
    - f_bashrc
    - f_gitconfig
    - f_clang-format_c
    - f_clang-tidy
    - f_emacs
    - d_emacs.d
    - f_clang-format_cpp
    - d_kdedefaults
    - d_kitty
    - d_hypr
    - f_dolphinrc
    - f_krunnerrc
    - d_rofi
    - d_wofi
    - d_waybar
    - d_dunst
    - d_eww
    - d_autostart
  lukac:
    dotfiles:
    - f_bashrc
    - d_nvim
    - d_kitty
    - d_i3
    - d_sxhkd
    - d_polybar
    - d_rofi
    - d_wallpapers
    - d_autostart
    - f_autostart.sh
    - d_dunst
    - f_gitconfig
    - f_gitignore
    - f_xinitrc
    - f_clang-format_c
    - f_clang-format_cpp
    - f_clang-tidy
    - d_bin
    - d_picom
    - f_editorconfig
    - d_fastfetch
    - f_monitorcontrol
    - f_xlight
    - f_idlelock
    - f_chwp
    - f_term.sh
    - f_profile
    - f_theming.sh
    - d_screenlayout
    - f_forgit.plugin.sh
