config:
  backup: true
  banner: true
  create: true
  dotpath: ../dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_polybar:
    dst: ~/.config/polybar
    src: config/polybar
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_clang-format_c:
    src: clang-format_c
    dst: ~/.clang-format_c
  f_clang-tidy:
    src: clang-tidy
    dst: ~/.clang-tidy
  f_emacs:
    src: emacs
    dst: ~/.emacs
  d_emacs.d:
    src: emacs.d
    dst: ~/.emacs.d
    chmod: '700'
  f_clang-format_cpp:
    src: clang-format_cpp
    dst: ~/.clang-format_cpp
profiles:
  home:
    dotfiles:
    - f_vimrc
    - f_xinitrc
    - d_polybar
  lukac-laptop:
    dotfiles:
    - f_vimrc
    - f_xinitrc
    - d_nvim
  /home/lukac/dotfiles/dotdrop/config.yaml:
    dotfiles:
    - d_nvim
    - f_bashrc
    - f_gitconfig
    - f_clang-format_c
    - f_clang-tidy
    - f_emacs
    - d_emacs.d
    - f_clang-format_cpp
