config:
  backup: true
  create: true
  dotpath: ../dotfiles
  ignoreempty: false
dotfiles:
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_autostart:
    src: config/autostart
    dst: ~/.config/autostart
    chmod: '700'
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_fastfetch:
    src: config/fastfetch
    dst: ~/.config/fastfetch
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    chmod: '644'
  d_profile.d:
    src: profile.d
    dst: ~/.profile.d
    chmod: '755'
  f_editorconfig:
    src: editorconfig
    dst: ~/.editorconfig
  f_tool-versions:
    src: tool-versions
    dst: ~/.tool-versions
  f_black:
    src: config/black
    dst: ~/.config/black
  f_pyrightconfig.json:
    src: config/pyrightconfig.json
    dst: ~/.config/pyrightconfig.json
profiles:
  lukac:
    dotfiles:
    - d_nvim
    - d_autostart
    - d_kitty
    - d_fastfetch
    - d_rofi
    - f_gitconfig
    - f_gitignore
    - f_bashrc
    - d_profile.d
    - f_editorconfig
    - f_tool-versions
    - f_black
    - f_pyrightconfig.json
